### PR TITLE
Charging function for Dacia Spring

### PR DESCRIPTION
**Pull request by JLorenz86**
Now, it is the final version.

### CODE REVIEW

**Comment by JLorenz86** [comment]
> Now, it is the final version.

**Comment by ovidiulaz7** [comment]
I'm sorry guys, I'm trying to figure out how to use the charging pause / resume for Dacia Spring from NodeRed but I can't figure it out. 

Can you show some usage examples somewhere? 🙈 

Thanks for the efforts!

**Comment by JLorenz86** [comment]
Hi,

you need to send a message to the "Renault-ze" Node. In my example, it is called "Baby Dacia".

To interrupt charging, you need the topic "set-charge-pause" and the boolean value true
To resume charging, you need the topic "set-charge-pause" and the boolean value false

Bildschirmfoto 2022-09-14 um 20 52 23

**Comment by ovidiulaz7** [comment]
Thanks a lot!

It's working! :D

**Pull request merged**
